name: deploy blog

on:
  push:
    branches:
      - develop
  schedule:
    - cron: '30 20 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout Develop
        uses: actions/checkout@v2.3.4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          ref: develop
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo
        run: hugo --minify

      - name: Upload Hugo to Server
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: 43.156.25.227
          username: blog_moozae_cn
          password: ${{ secrets.FTP_MIRROR_PASSWORD }}
          local-dir: ./public/
          server-dir: /
